### ISSUE TITLE
Erroneous line in toolchain setup page on wiki.

### ISSUE THREAD

**Issue by tylercrumpton** [esp8266/esp8266-wiki#22]
In the "[Setting up the Espressif SDK](https://github.com/esp8266/esp8266-wiki/wiki/Toolchain#setting-up-the-espressif-sdk)" section of the [Toolchain page](https://github.com/esp8266/esp8266-wiki/wiki/Toolchain), there is a line `mkdir ESP8266_SDK` that messes up the process. Later, at the `mv esp_iot_sdk_v0.9.3 ESP8266_SDK` line, the intended rename is instead turned into a move into the previously created directory.

Solution:  The `mkdir ESP8266_SDK` should be removed.

**Comment by jcmvbkbc** [comment]
Fixed. Thanks.
