### ISSUE TITLE
Example Request: Establish a wifi-direct (p2p) connection to android device

### ISSUE THREAD

**Issue by ckybonist** [esp8266/esp8266-wiki#49]

**Comment by pmcdonaldgit** [comment]
I would appreciate something like this as well...

**Comment by Nitinrajyadav** [comment]
Is it even possible to establish a wifi-direct (p2p) connection to ESP an Android device?

ok I look up a little more and I found this
https://github.com/esp8266/Arduino/issues/2343

**Comment by mefitzgerald** [comment]
this might help.. http://www.labradoc.com/i/follower/p/notes-esp8266
