### ISSUE TITLE
Wiki vandalized, contact form not working

### ISSUE THREAD

**Issue by shoeffner** [esp8266/esp8266-wiki#89]
I visited the wiki today (https://www.esp8266.com/wiki/doku.php) and the start page contains only an SEO Advertisement.
When I tried to use the contact form at esp8266.com it denied me twice because of wrong security answers and "already taken" user names, which is weird when I only want to contact someone. The security question asked twice for the 1st and 3rd character of `@.$....` (don't remember the ....), but apparently "At Dollar" was not the correct response.

**Comment by themindfactory** [comment]
Thanks for the heads up, the correct answer is @$ and I. Reverted the wiki
back...

**Comment by shoeffner** [comment]
Thanks!
